# Generated by Django 2.2.14 on 2022-12-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221203_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('about_us', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
