# Generated by Django 2.2.14 on 2022-12-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='user_name',
            new_name='user',
        ),
    ]
