# Generated by Django 2.2.14 on 2022-12-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221211_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='slug',
            field=models.SlugField(default='eshaan', unique=True),
        ),
    ]
