# Generated by Django 2.2.14 on 2022-12-21 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20221211_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='work',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, upload_to='authorImg'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='Porduct'),
        ),
    ]
