# Generated by Django 2.2.14 on 2022-12-21 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20221221_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='Facebook_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='Youtube_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='github_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='instagram_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='linkedin_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='project_Img',
            field=models.ImageField(blank=True, upload_to='project_images'),
        ),
    ]
