# Generated by Django 2.2.14 on 2023-02-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minCartValue',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
